#!/bin/sh
if [ -f /var/lib/misc/custom-set-vm-hostname ]
then
	echo "Hostname already set - skipping!"
	exit 0
fi
vm_name=""
if [ -x /usr/bin/vmtoolsd ]
then
	vm_name=$(vmtoolsd --cmd "info-get guestinfo.custom.name" 2>/dev/null)
	if [ -z "$vm_name" ]
	then
		echo "$0 hostname not changed - missing guestinfo.custom.name"
		exit 0
	fi
fi
if [ -x /usr/sbin/VBoxControl ]
then
	vm_name=$(VBoxControl --nologo guestproperty get custom.name)
	if [ $? -eq 0 ]
	then
		vm_name=${vm_name#Value: }
	else
		echo "$0 hostname not changed - missing custom.name"
		exit 0
	fi
fi
if [ -n "$vm_name" ]
then
	/usr/bin/hostnamectl set-hostname $vm_name
	echo "$0 hostname auto changed to $vm_name"
	touch /var/lib/misc/custom-set-vm-hostname
fi
exit 0
